### ISSUE TITLE
2. séria SuŠi

### ISSUE THREAD

**Issue by krtko1** [kockatykalendar/data#13]
prečo ju máme zhruba 3 krát?
data/2020_21/11_july/ipho.yml
data/2020_21/12_august/2_susi.yml
data/2020_21/04_december/2_susi.yml

**Comment by ano95** [comment]
a prečo ipho.yml :smile: 

ináč, dohodnite sa ideálne, či to píšete Suši alebo SuŠi

**Comment by krtko1** [comment]
fakt netuším a to susi zisim, ja používam SuŠi ako si si mohol všimnúť ale ako pozerám na stránku, tak tam vyhráva Suši, tak teraz neviem, dal som hlasovať tak uvidíme

**Comment by ano95** [comment]
@krtko1 status?

**Comment by krtko1** [comment]
Nooo, je to zhruba 50 na 50. 4 vedúci sú za SuŠi, 3 za Suši lebo je to na väčšine miest. Takže neviem.

**Comment by ano95** [comment]
Suši vyzerá inteligentnejšie :smile: a používa sa takmer všade, takže asi by som ho používal
