### ISSUE TITLE
Ako definovať súťaž s open vekovou kategóriou?

### ISSUE THREAD

**Issue by krtko1** [kockatykalendar/data#26]
Občas sa aj v akciách čo v kalendári máme taká akcia objaví. Suši má open kategóriu, myslím, že aj attomaty, adventný kalendár KMS, Brieždenie, ...

S tým je spojené aj zobrazovanie týchto udalostí. Aktuálne máme required iba minimálny ročník (čo asi pre všetky tieto akcie existuje) otázka je však ako sa postaviť k maximu (aktuálne jednoročníkové akcie nemajú maximum).

Navrhujem aby jednoročníkové akcie mali aj maximum a pridáme pre špeciálne zobrazenie na frontend. A aby open súťaže nemali maximum a tiež im pribudlo nejaké špeciálne zobrazenie na stránke. Namiesto maximálneho ročníku open? Neviem úplne čo by bolo rozumné.

Druhá možnosť je pridať možnosť nastaviť max na open alebo možno aj min. Prípadne môžme na tento účel použiť iné slovo. 

Tak či tak si to vyžaduje zmeny v dátach a frontende ostatne s tým mierne súvisí <https://github.com/kockatykalendar/frontend/issues/72>. Otázka teda na @Zajozor a @ano95, ktorým smerom sa chceme vybrať?

**Comment by Zajozor** [comment]
> Navrhujem aby jednoročníkové akcie mali aj maximum a pridáme pre špeciálne zobrazenie na frontend. A aby open súťaže nemali maximum a tiež im pribudlo nejaké špeciálne zobrazenie na stránke.

Za mna takto v datach :)
Na frontende mozeme rozobrat potom napady, ale v zasade nieco take ako vravis.

**Comment by ano95** [comment]
Akože, ak je to úplne open, nedáva mi zmysel definovať minimálny ročník :thinking:

**Comment by Zajozor** [comment]
Zamyslal som sa nad tym a napadlo mi - nevieme mat specialnu hodnotu v tych min/max polickach, ze "unspec"/alebo nieco v tom zmysle ?

a povinne min aj max v tej scheme?
Potom by to mozno bolo viac jednoznacne/menej nekonzistencii by vznikalo..

**Comment by krtko1** [comment]
No podľa mňa je v pohode taká možnosť

ut 22. 12. 2020 o 14:52 Matej Zajo Kralik <notifications@github.com>
napísal(a):

**Comment by ano95** [comment]
Jo, len by som skôr použil štandardne null / ekvivalent.

**Comment by Zajozor** [comment]
to znie fajn - tak ak sa niekomu chce urobit PR kde budu obe povinne a budu moct byt aj null + poupravujeme existujuce eventy aby tomu vyhovovali - smelo do toho :)
