### ISSUE TITLE
Údaje o organizátoroch

### ISSUE THREAD

**Issue by gardenerik** [kockatykalendar/data#38]
Mali by sme pre budúcnosť niekde centrálne ukladať dáta o organizátoroch, aby sa nemuseli opakovať vo frontende, ical a prípadne daľších subprojektoch.

Asi chceme vedieť:
* názov v dátach
* zobrazovaný názov
* logo?
* web stránka??

**Comment by krtko1** [comment]
za mňa asi všetko z toho. Teda stránka mi znie rozumne a logo asi tiež.
