### ISSUE TITLE
missing/outdated p-mat camps

### ISSUE THREAD

**Issue by Zajozor** [kockatykalendar/data#39]
tuto zimu pikomat starsi chyba uplne lol
a teda vsetky tri by bolo dobre oznacit ako zrusene.

@krtko1 nenasiel by si si na to 10 min plz ?

**Comment by Zajozor** [comment]
susi zrejme tiez nebolo
a stromu by sme sa mohli popytat - nech mame tie zimne komplet porusene

**Comment by krtko1** [comment]
fixed in #41 and susi in #40. Ešte ten strom, @miskadlugosova neozveš sa im?

**Comment by krtko1** [comment]
@ano95 @Zajozor bol som v tom, že som toto fixol ale stále vidím napríklad:
![2021-01-19-184942_grim](https://user-images.githubusercontent.com/21214184/105073331-38811300-5a87-11eb-9dd1-7cce4246ea2d.png)

**Comment by Zajozor** [comment]
zvlastne. api vracia spravnu vec. Moznoo fail v template logike? viem to ale pozriet az zajtra.

**Comment by ano95** [comment]
@krtko1 `canceled` vs `cancelled` :joy:

**Comment by krtko1** [comment]
och, prečo to nefaillo?

**Comment by ano95** [comment]
Lebo technicky to nie je nesprávne :joy:

**Comment by krtko1** [comment]
akože nedá sa kontrolovať že tam nieje nič navyše? Ja som sa to snažil nájsť ale nenašiel som.
